#
# This pipeline needs the following tasks installed in the cluster:
#   - cleanup        (your custom task from tekton/tasks.yaml)
#   - git-clone      (from Tekton catalog / hub)
#   - flake8         (your custom task from tekton/tasks.yaml)
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      description: The git repo URL to clone from
    - name: branch
      type: string
      default: main
    - name: build-image
      type: string
      description: Image to build and push (reserved for later stages)
  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - init
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: path
          value: "service"
        - name: args
          value: "--count --max-complexity=10 --max-line-length=127 --statistics"
